### ISSUE TITLE
you can set text using these function

### ISSUE THREAD

**Issue by qiangqiang101** [mrdiamonddirt/WeazelNewsCam#7]
SET_TEXT, char newsTitle, char newsSubtitle
SET_SCROLL_TEXT, int, int, char newsThirdtitle
DISPLAY_SCROLL_TEXT, int, int, char newsThirdtitle

![headline](https://user-images.githubusercontent.com/11488961/50720075-31c21600-10e1-11e9-9044-afdd45d10ecb.jpg)

**Comment by qiangqiang101** [comment]
you can use game text label subtitle "MPTV_SBTTL", "MPTV_CESTTL"
and above Breaking news "MPTV_TICK0", "MPTV_TICK1", "MPTV_TICK2", "MPTV_TICK3", "MPTV_TICK4", "MPTV_TICK5"
and the Breaking news text "MPTV_TITLE"
![headline](https://user-images.githubusercontent.com/11488961/50720116-dd6b6600-10e1-11e9-8bc6-5428b6560828.jpg)

**Comment by qiangqiang101** [comment]
be sure the text function only called once, not in loop

**Comment by Danny9865** [comment]
is there any examples of this guys, also anyway to change the weazel news at the bottom right to personalise it? thanks in advance

**Comment by mrdiamonddirt** [comment]
thanks only just saw this post implemented in the script and pushed an edit to qb-newsjob to reflect the same change appreciate your help ☺
